version: '3.8'

services:
  blog_api:
    build:
      context: ./services/blog_api
      dockerfile: Dockerfile.ci
    command: pytest ./api/
    env_file:
      - ./.env.dev
    depends_on:
      - db
    
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blog_db
