# Generated by Django 4.1.2 on 2022-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_full_img_alter_post_thumb_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb_img',
            field=models.ImageField(blank=True, upload_to='thumb_imgs'),
        ),
    ]
