name: blog_app_ci

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: github_actions
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run docker-compose
      run: docker-compose -f .github/docker-compose.ci.yml up -d --build
    - name: Test app
      run: docker-compose exec blog_blog_api_1 pytest ./api/
