name: blog_app_ci

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run docker-compose
      run: docker-compose -f docker-compose.ci.yml up -d --build
    - name: View test results
      run: docker logs -f blog_blog_api_1
